configuration:
  system:
    arp:
      aging_timer: "5"
      gratuitous_arp_on_ifup: null
      purging: null
    auto_snapshot: null
    domain_name: fountainhead.home
    domain_search: fountainhead.home
    extensions:
      providers:
        - license_type:
            deployment_scope: commercial
            name: juniper
          name: juniper
        - license_type:
            deployment_scope: commercial
            name: juniper
          name: chef
    host_name: "{{ inventory_hostname }}"
    login:
      class:
        - idle_timeout: "10"
          name: MAINTENANCE-ID
          permissions: maintenance
        - idle_timeout: "10"
          name: SUPERUSER-ID
          permissions: all
        - idle_timeout: "10"
          name: VIEW-ID
          permissions: view
      message: '********************************* WARNING *********************************\n*                                                                         *\n* This system is for authorized users only. This, and any other sessions, *\n* can and will be monitored to determine whether or not it is being used  *\n* by an authorized user.                                                  *\n*                                                                         *\n* By logging into this system, you are consenting to such monitoring, and *\n* are advised that the system administrators retain the right to use any  *\n* recorded session as evidence of criminal activity, if such activity is  *\n* monitored.                                                              *\n*                                                                         *\n********************************* WARNING *********************************'
      retry_options:
        backoff_factor: "10"
        backoff_threshold: "3"
        tries_before_disconnect: "3"
      user:
        - authentication:
            encrypted_password: $6$FgsqZPh4$c.DcqHDQLA1gTP0Ok6fC6on30ABVfyJK3F3Y5XKIP8fGu0G0lIWcHiS.sdTNJnGvskywFmEBbZ9Xwo0poRWV90
            ssh_rsa:
              name: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUCqloz2uqBHAHv0B8eIRVUDjuGJopQ+R1uVFsYPADeYEnJhlfVxF/jGaTZpK7gHZpaFDhKwm98ouZiwb6fVx0TCKFS4UJTM4qMjdrjzERCFLCyvml/x7YtTmgykHMedxdHJbXeX6FQ7TZ1DHoYPQ8oa1mjeFuj+rY1fa5WIz4Y2rmaukQ+N9OQt4GeaToKFhFtDMKB3zUXJ+TjUaFCIhewqwr8SSTzAdNh87epIUV01/NmRNZK19QXS+ahJfKaZiRExiesfw+qUeO7C/KY9QP5TfDuo6lRy9NfXbll4tOKQFD8BG+TsBzKpp5xjA6dM8wlAx3nORuDZ2P1mt4Y/uQVOckcWN0Kiin7q+o/iAp6yjsOaGtdTLHgBOZNBwD4EeAXO4lPjZR14jzQUKykMx9Y2cB47K4dMi5Co6j+sTBJ0FXCL4sJ7EDKMBYPQk7FcGSza8J9UsBne64C+iAzGN+mUlYRNqj3qIjtY/vRpSrnKbyzDABr7Xz+CgsvqYTowGU7RuW723JFpA2WlBM9XYz4rJFuHTERzQUH9V/Y+jze05BpW7x+52LuKrTMmMR6Ykje4bo4fryCsf4w/jgSdq08Yt3Qd7j73C0IxYXpE5Ib57sN+qoKVVuMhVhXrTtZDJwtIGopKK2z8YmIqvIDUOlcK+IYWwpf2xWEDMMOZnkzw== ansible awx tower ssh keys
          class: super-user
          name: ansible
          uid: "3000"
        - authentication:
            ssh_rsa:
              name: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDS2gv7pgItRc0DlcXelZPUv7tojJtiAOEGkMlaHtUmsphI27L9tFEn5waFBMh6WbeCqkitaV8XpxsK3KCW05tDjLx//VOS+KYy4bKxEHkTIfWYCgASP4RQbXuGpeAN72/MRTWo8yU33l2fRrwzzlL/b/X+jcJR2zGriQpcBQ9K8aTDvk3jNyunQGL+PAFYrLO4nUxWLQbJFXM0K1Y4IFmPU5/szdvcBCNMzh66KbyD4cwTpvI2sFJ1gtg4ld8/8e8fW82Jx7xM5u5adrEQsrg/5R7MBrTtbtNMy2jxxfAldUlzNJ+LgONXz2bqGL/GGC30NdwXcDBuafRZXxHECgnft2BYyh4OZE2ChLSjhKh4pnEFBpKW0z55IM2AmqLjTvBOd03JoxOkbppofb8+g7VjhyRgjUUPsygAsUiKyTiKW8D6nY991A/tu0TgQ5lakvyaCZj2EB72W1KE5YS4tddHMkEzfW80cm8OCFHDgzypOoCMFZQHsqbZfAh0qV21tCsZzVrxL07JRvjkFRdb+feqvryKdDkxV8vaomWWBMfF7W7iz4PyHkm/Oylb1/bEvkDhpz5ep2iS11v0E4brFpUkp8OxvgmbUCMx4djqmopVLGGM8qH6a0ZRpVKrKJY3xxsHhhAmisNcEW1xx3GKUQsLg9w6/SIYAivp0ISVO0dj3w== cremsburg_juniper
          class: super-user
          name: cremsburg
          uid: "3001"
        - authentication:
            ssh_rsa:
              name: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMiya2J1GVRh0dHBHTb90TxArVNZf7mWiJxPbLtKRiHp7jz/BLTAlChAGn/67NGQ5HCJuMv5B1IPY6DRRc8uwwxpYtscGMpzXSlA0bdXJfFg7fVfJdidl+ajy9mLJ3DCbrL1ovRmDAqQdoq+oOk9apeIfiMMPsduOhtJ41qKbO5WVOYrrZIk6WORWqzGoNVUc3otcsbi5G4n4GEF1DlcKh7l93SoY5j+DLwG9W+vp5ObC/1NfIE4A4XnVaXUF7mE15f+RIe7W4kNrVoUVP8qpMGcsnCKva+gkKOeM+H5eDNHNA8uKvaU8rE5WAZL9ZwskZscWlzcvTlovG2iz/ssunhdusNOQ8+aHNb4qGIFpLREG8Ll9dti8mfSw1VpArJmsiqsKXSV5LuOg8TysyINDi60tumNAxTM8Zi9MLFhz5Y9tBt2ncd3tsVgb0FbkIfx+ox5r38GclStr0+rLWCN4nhU84zjbraCgzS90JjzhM9e9G5COgJTbV9dSBTqHY1BFHgluACu/SEDqw+FpaZ1/50fn25Vxh8mVpF6JNXsecLxqauDUB5RK1/mCMjYx/QDpb4pjI+K/VdhYTi44DAuBEcQQ1wvb5o14LQ4rqfoMh/uWJUWXIqOowQhMNQDF7gnqxTxhuwYTSogBJUzMDj0Cb9WOhEq0WOuxuAnZh9qa9Gw== healthbot lab fun time
          class: super-user
          name: healthbot
          uid: "3003"
        - authentication:
            encrypted_password: $6$s8L/YliX$0uji4ZNG4mUt59noVjvyd9NlcpKx88h5BN3sqeHoAGaDsfyJMqsNFGUs.LGhvyT1iP3faYNA1CTqxxTQ0MQRW1
            ssh_rsa:
              name: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCWRvTNMu/WTbpowURuKduMBaARWfNoyyXXJxbpt/h6QOd8wYx5Mt1YeoCvdUVFHgmFFxXJc6cmV3Oe8IHReF8NEgW1x2MA+Eg/M6GmKmWVUaJvlUO0raggwsWFk1YQkDIn+qaO46lDEuz0hhpR9INKQ30M6W/3DRojDfVNH9XjpFGB7KCnfA0GHvNGyEakwu7WvfqQWO2D0hPg85SCu9bsuifpLa1qm4FPIqqQqIN0AMlNOdaGnVIE5vqnTsmqi6T18R0qXLPs2vtXbpKR7s2awelVDZovwrQABDah87TCpudyrFWOR00sA/+q9uOVBR9gNnHCjX9lw5exhp71Yq8kmcgpzo9ejevShFUQrGVoist8wwXDI0BJyfqxFMLIKLc8wVHT309y6Lj0jxtfyd98Ngiv3wMCi80AcpukJDLVco6QNrqBk5KPin/2XFoIpSWmkTrOh5nFgHL4HrUAiOmvV3h60WaO6SxkcHp7x8fnt/YnfzXB90Hiy8b/dqi5wFEeRAgKnGo97LvFxbM8UfKOZKVB9cKSqXaloL9Fke56HwTIGFPFMXccOxjfsDdlpHJ7PiPbwq4X6z4VyY3Tyo8c5sxcaKHRX8IQtzId/pn2JvoUVGdiF6G9ZoYbgCGYeWsjczxE4Y/PJwoMm1W5dU47F58BKh/im+i52bmdC1sIvw== apple-pc-01.redtail.local
          class: super-user
          name: packetferret
          uid: "3002"
    name_server:
      - name: 10.255.127.251
      - name: 10.255.127.252
    no_redirects: null
    ntp:
      server:
        name: 10.255.127.16
      source_address:
        name: "{{ ansible_host }}"
    root_authentication:
      encrypted_password: $6$.9OWAuFK$iiXPju/x8lyIhSWeJ.vVqTZkTI5u6XzlQyhakYkkVdlQ4fqbQmjFJ2POJ9fPtykTt2l7SszK8qx06Bg3x0NNP1
    scripts:
      language: python
      op:
        file:
          name: toggle.py
    services:
      ftp: null
      netconf:
        ssh: null
      rest:
        enable_explorer: null
        http:
          port: "8080"
      ssh:
        connection_limit: "10"
        max_sessions_per_connection: "32"
        protocol_version: v2
        rate_limit: "10"
        root_login: allow
    syslog:
      file:
        - contents:
            - name: any
              notice: null
            - info: null
              name: authorization
          name: messages
        - contents:
            any: null
            name: interactive-commands
          name: interactive-commands
      host:
        - contents:
            any: null
            name: any
          name: 10.255.127.5
          port: "5514"
          source_address: "{{ ansible_host }}"
        - contents:
            any: null
            name: any
          name: 10.255.127.26
          source_address: "{{ ansible_host }}"
      user:
        contents:
          emergency: null
          name: any
        name: "*"
    time_zone: America/Chicago
